en:
  languageName: English
  weight: 2

ru-ru:
  languageName: Русский
  weight: 1
  params:
    dateFormat: '02-01-2006'
    description: 'GroSport, спортивное питание Екатеринбург, High5, Sponser, Sis, Zipvit, Elite, Powerup, Power up, Powerbar, Power bar, Isostar, Multipower, Squeezy, GU, SaltStick, Nutrend, ON, NOW, Maxler, Natrol, Optium Nutrition'
    keywords: 'Hugo, Bootstrap, GroSport, gro-sport, ГроСпорт, гро-спорт, гро, gro, спортивное питание, спортивное питание для выносливости, питание для бега, бег, лыжи, кросс, велогонка, длительная, марафон, полумарафон, ультрамарафон, marathon, Transural, трансурал, триатлон, изотоник, isotonic, энергетические гели, питание на марафон, гели на марафон, high5, sponser, sis, zipvit, elite, powerup, power up, powerbar, Nutrend, power bar, электролиты, isostar, multipower, squeezy, арена, спортивное питание екатеринбург, магазин спортивного питания, солевые таблетки, айронмен, ironman, GU, SaltStick, Zet, лыжная смазка, Nutrend, ON, NOW, Maxler, Natrol, Optium Nutrition'
