# email: user@domain.tld
github: Rupreht/hugo-grosport-blog
# gitlab: yourgitlabusername
# linkedin: yourlinkedinusername
# xing: yourxingusername
# stackoverflow: yourstackoverflowuserid
# twitter: yourtwitterusername
# weibo: yourweibousername
# zhihu: yourzhihuusername
# instagram: yourinstagramusername
# quora: yourquorausername
# tumblr: yourtumblrusername
# reddit: yourredditusername
# telegram: yourtelegramusername
# qq: yourqqnumber
# dockerhub: yourdockerhubusername
# bitbucket: yourbitbucketworkspaceid
# kaggle: yourkaggleusername
# medium: yourmediumusername # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm: yourlastfmusername
# bilibili: yourbilibiliuserid
# youtube: youryoutubechannelid
# discord: yourdiscordinvitecode
# discourse: https://yourforum.tld
# tiktok: yourtiktokusername
# pinterest: yourpinterestusername
# mastodon: yourmastodonusername
# liberapay: yourliberapayaccount
# tipeee: yourtipeeeaccount-fr
vk: grosport.skischool
